#Data Preprocessing Tools

##Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

##Importing the dataset

In [ ]:
dataset = pd.read_csv('50_Startups.csv')
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [ ]:
x = dataset.iloc[:,:-1].values
y= dataset.iloc[:,-1].values
# print(x)
# print(y)

##Taking care of the missing data

In [ ]:
missing_data = dataset.isnull().sum()
missing_data

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [ ]:
# from sklearn.impute import SimpleImputer
# imputer = SimpleImputer(missing_values =np.nan,strategy='mean')
# imputer.fit(x[:,1:3])
# x[:,1:3]=imputer.transform(x[:,1:3])

In [ ]:
# print(x)

##Encoding categorical data

###Encoding independent variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])] ,
                       remainder='passthrough' )

In [ ]:
x1=np.array(ct.fit_transform(x))
x1

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

###Encoding dependent variable

In [ ]:
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# y1=le.fit_transform(y)
# y1

##Splittinf dataset into training_dataset and test_dataset

In [ ]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test = tts(x1,y,test_size =0.2,random_state=1)

In [ ]:
print(x_train)

[[1.0 0.0 0.0 63408.86 129219.61 46085.25]
 [1.0 0.0 0.0 38558.51 82982.09 174999.3]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 28663.76 127056.21 201126.82]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 23640.93 96189.63 148001.11]
 [1.0 0.0 0.0 0.0 116983.8 45173.06]
 [0.0 1.0 0.0 75328.87 144135.98 134050.07]
 [0.0 1.0 0.0 73994.56 122782.75 303319.26]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 27892.92 84710.77 164470.71]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 0.0 1.0 1000.23 124153.04 1903.93]
 [0.0 0.0 1.0 77044.01 99281.34 140574.81]
 [0.0 1.0 0.0 67532.53 105751.03 304768.73]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 1.0 0.0 55493.95 103057.49 214634.81]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 1.0 0.0 61994.48 115641.28 91131.24]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 66051.52 182645.56 118148.2]
 [1.0 0.0 0.0 22177.74 154806.14 28334.72]
 [1.0 0.0 0.0 46426.07 157693.92 210797.67]
 [0.0 1.0 0.

In [ ]:
print(x_test)

[[0.0 0.0 1.0 72107.6 127864.55 353183.81]
 [0.0 0.0 1.0 46014.02 85047.44 205517.64]
 [1.0 0.0 0.0 28754.33 118546.05 172795.67]
 [0.0 0.0 1.0 20229.59 65947.93 185265.1]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 0.0 1.0 542.05 51743.15 0.0]
 [0.0 0.0 1.0 65605.48 153032.06 107138.38]
 [0.0 1.0 0.0 1315.46 115816.21 297114.46]
 [0.0 0.0 1.0 61136.38 152701.92 88218.23]]


In [ ]:
print(y_train)

[ 97427.84  81005.76 111313.02  90708.19 122776.86  71498.49  14681.4
 105733.54 110352.25 134307.35  77798.83 125370.37  64926.08 108552.04
 108733.99 166187.94  96778.92 132602.65  99937.59 146121.95 103282.38
  65200.33  96712.8  124266.9  118474.03 107404.34 156122.51 155752.6
  42559.73 191792.06 126992.93 192261.83 129917.04 156991.12 144259.4
 149759.96 152211.77 141585.52  69758.98  89949.14]


In [ ]:
print(y_test)

[105008.31  96479.51  78239.91  81229.06 191050.39 182901.99  35673.41
 101004.64  49490.75  97483.56]


##Feature Scaling

In [ ]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# x_train[:,3:] = scaler.fit_transform(x_train[:,3:])
# x_test[:,3:] = scaler.transform(x_test[:,3:])

# feature scaling is not required for Multiple Linear Regression

In [ ]:
# print(x_train)

In [ ]:
# print(x_test)

#Data Modelling

##Training the Multiple Linear Regression model on the training set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

##Predicting the test set results

In [ ]:
y_pred=regressor.predict(x_test)
y_pred

array([114664.41715867,  90593.15531621,  75692.84151574,  70221.88679652,
       179790.25514872, 171576.92018521,  49753.5875203 , 102276.65888936,
        58649.37795761,  98272.02561131])

In [ ]:
n = len(y_pred)
print(np.concatenate(( y_pred.reshape(n,1),y_test.reshape(n,1) ),1))

[[114664.41715867 105008.31      ]
 [ 90593.15531621  96479.51      ]
 [ 75692.84151574  78239.91      ]
 [ 70221.88679652  81229.06      ]
 [179790.25514872 191050.39      ]
 [171576.92018521 182901.99      ]
 [ 49753.5875203   35673.41      ]
 [102276.65888936 101004.64      ]
 [ 58649.37795761  49490.75      ]
 [ 98272.02561131  97483.56      ]]


## Visualising the training set results

In [ ]:
# plt.scatter(x_train,y_train,color='red')
# plt.plot(x_train,regressor.predict(x_train),color='blue')
# plt.title("Salary v/s Experience -------- Training Set")
# plt.xlabel('Years of Experience')
# plt.ylabel('Salary')
# plt.show()

## Visualising the test set results

In [ ]:
# plt.scatter(x_test,y_test,color='red')
# plt.plot(x_test,regressor.predict(x_test),color='blue')
# plt.title("Salary v/s Experience -------- Test Set")
# plt.xlabel('Years of Experience')
# plt.ylabel('Salary')
# plt.show()